# params.yaml - Hyperparameters and Configuration
# Central configuration for MLOps pipeline

# Data Preprocessing Parameters
preprocessing:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  handle_outliers: true
  outlier_method: "clip" # clip or remove
  imputation_strategy: "median"

# Feature Engineering Parameters
features:
  use_feature_selection: true
  n_features: 20
  feature_selection_method: "random_forest" # random_forest, statistical, or both
  create_interactions: true
  create_polynomial: true
  polynomial_degree: 2
  use_pca: false
  n_pca_components: 10

# Model Training Parameters
models:
  # Random Forest
  random_forest:
    n_estimators: [100, 200]
    max_depth: [10, 20, None]
    min_samples_split: [2, 5]
    min_samples_leaf: [1, 2]

  # XGBoost
  xgboost:
    n_estimators: [100, 200]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.3]
    subsample: [0.8, 1.0]

  # LightGBM
  lightgbm:
    n_estimators: [100, 200]
    max_depth: [5, 10, -1]
    learning_rate: [0.01, 0.1]
    num_leaves: [31, 50]

  # Gradient Boosting
  gradient_boosting:
    n_estimators: [100, 150]
    max_depth: [3, 5]
    learning_rate: [0.01, 0.1]

  # Logistic Regression
  logistic_regression:
    C: [0.1, 1.0, 10.0]
    max_iter: [1000]

  # SVM
  svm:
    C: [0.1, 1.0, 10.0]
    kernel: ["rbf", "linear"]

  # KNN
  knn:
    n_neighbors: [3, 5, 7]
    weights: ["uniform", "distance"]

  # AdaBoost
  adaboost:
    n_estimators: [50, 100]
    learning_rate: [0.5, 1.0]

# Model Evaluation Parameters
evaluation:
  cv_folds: 5
  scoring_metric: "f1" # for classification
  regression_metric: "r2"
  threshold_accuracy: 0.85
  threshold_f1: 0.80
  threshold_r2: 0.70

# MLflow Tracking
mlflow:
  tracking_uri: "mlruns"
  experiment_name: "migraine_prediction"
  run_name_prefix: "run"
  log_artifacts: true
  log_models: true

# Model Drift Detection
drift_detection:
  enabled: true
  psi_threshold: 0.2 # Population Stability Index
  data_drift_threshold: 0.05
  model_performance_threshold: 0.10 # 10% performance drop

# Monitoring and Alerts
monitoring:
  enabled: true
  alert_on_drift: true
  alert_on_performance_drop: true
  performance_window: 100 # number of predictions
  metrics_refresh_interval: 60 # seconds

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  reload: true
  workers: 4
  timeout: 30

# Deployment
deployment:
  model_registry: "mlflow"
  deployment_target: "kubernetes" # docker, kubernetes, or cloud
  min_replicas: 2
  max_replicas: 10
  cpu_request: "500m"
  memory_request: "512Mi"
  cpu_limit: "1000m"
  memory_limit: "1Gi"

# Security (MLSecOps)
security:
  enable_authentication: true
  enable_rate_limiting: true
  rate_limit: 100 # requests per minute
  enable_input_validation: true
  enable_model_encryption: false
  log_predictions: true
